[package]
name = "gol_rust"
version = "0.1.0"
authors = ["Adan Alvarado <adan.alvarado7@gmail.com>"]

[dependencies]
pancurses = "0.7"
ndarray = "0.7.2"
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
